### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by lhqing** [lhqing/wmb2023#1]
## General
- [ ] Generate MCDS
- [ ] Generate CoolDS
- [ ] Generate BaseDS
- [ ] Handle XDS and xarray basics

## Figure 1
- [x] mapping pipeline
- [x] clustering template

## Figure 2
- [x] mC-RNA Integration template
- [x] mC-ATAC integration template

## Figure 3
- [x] mC-MERFISH integration template

## Figure 4
- [ ] snm3C imputation pipeline
- [ ] Compartment calling
- [ ] Domain calling
- [ ] Pixel ANOVA analysis
